//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// LT MainExecution.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_FORMVIEW_ID_LIST            101
#define IDD_DLG_BARCODE                 102
#define IDD_PROPPAGE_OPTION             103
#define IDB_BOTTOM_LEFT                 104
#define IDR_POPUP_EDIT                  105
#define IDP_SOCKETS_INIT_FAILED         106
#define IDB_BOTTOM_MIDDLE               107
#define IDB_BOTTOM_RIGHT                108
#define IDB_MIDDLE_LEFT                 109
#define IDD_DLG_MODIFY_STEP             109
#define IDB_MIDDLE_RIGHT                110
#define IDB_TOP_LEFT                    111
#define IDB_TOP_MIDDLE                  112
#define IDB_TOP_RIGHT                   113
#define IDD_DLG_FULLSCREEN              114
#define IDD_TEST_FORM                   115
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define IDD_DLG_MODIFY_EES              126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDI_ICON_SEM                    130
#define IDI_ICON_KEYBOARD               131
#define IDD_DLG_ACESS_MODE              199
#define ID_SET_STYLE                    201
#define IDS_STR_OPTION                  202
#define IDS_STR_OPT_PAGE_01             203
#define IDS_STR_OPT_PAGE_02             204
#define IDS_STR_OPT_PAGE_03             205
#define IDS_STR_OPT_PAGE_04             206
#define IDS_STR_OPT_PAGE_05             207
#define IDS_STR_OPT_PAGE_06             208
#define IDS_STR_OPT_PAGE_07             209
#define IDS_STR_OPT_PAGE_08             210
#define IDS_STR_OPT_PAGE_09             211
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP_CHECK                311
#define IDB_BITMAP_CHECKNO              312
#define IDB_OUTPUT_TAB_ICONS            316
#define IDI_ICON_LOGO                   317
#define IDI_ICON_Luritech               318
#define IDI_ICON_CONNECT                320
#define IDD_DLG_CHK_PASSWORD            323
#define IDD_DLG_MODULE_PROGRESS         324
#define IDB_SELECT                      339
#define IDB_SELECT_NO                   340
#define IDB_CHECKED                     341
#define IDB_UNCHECKED                   342
#define IDB_SELECT_16                   343
#define IDB_SELECTNO_16                 344
#define IDD_DLG_CHANGE_PASSWORD         366
#define IDB_CHECKED_16                  368
#define IDB_UNCHECKED_16                369
#define IDB_CHECKED_8                   370
#define IDB_UNCHECKED_8                 371
#define IDI_ICON_DEVICE                 374
#define IDI_ICON_TSP                    375
#define IDB_TEST_START                  378
#define IDB_TEST_START_R                380
#define IDB_LOAD_FILE                   382
#define IDB_LOAD_FILE_G                 383
#define IDB_START                       384
#define IDB_STOP                        385
#define IDB_BITMAP_Luritech             387
#define IDB_ARROW_UP                    388
#define IDB_ARROW_RIGHT                 389
#define IDB_ARROW_LEFT                  390
#define IDB_ARROW_DOWN                  391
#define IDC_MODULE                      1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON_REPORT_USER_CHANGE   1002
#define IDC_BUTTON_REPLY                1002
#define IDC_REPORT_TRANSACTIONID        1003
#define IDC_REPORT_TIMESTAMP            1004
#define IDC_STATIC_REPORT_TimeStamp     1005
#define IDC_STATIC_REPORT_HEAD          1006
#define IDC_STATIC_REPORT_BODY          1007
#define IDC_STATIC_REPORT               1008
#define IDC_REPORT_EQUIPMENTID          1009
#define IDC_REPORT_IPADDRESS            1010
#define IDC_STATIC_REPORT_IPADDRESS     1011
#define IDC_ED_PASSWORD                 1012
#define IDC_STATIC_REPORT_EQUIPMENTID   1012
#define IDC_LIST_DLG_TRANS_MSG          1013
#define IDC_STATIC_REPORT_transactionId 1013
#define IDC_ST_PASSWORD                 1014
#define IDC_REPORT_USERID               1014
#define IDC_ST_DLG_TRANS_STATE          1015
#define IDC_STATIC_REPORT_USERID        1015
#define IDC_REPORT_EESMODE              1016
#define IDC_STATIC_REPORT_EESMODE       1017
#define IDC_STATIC_REQUEST_RETURN       1018
#define IDC_STATIC_REQUEST              1019
#define IDC_STATIC_REQUEST_HEAD         1020
#define IDC_STATIC_REQUEST_BODY         1021
#define IDC_REQUEST_TRANSACTIONID       1022
#define IDC_STATIC_REQUEST_transactionId 1023
#define IDC_STATIC_REQUEST_TimeStamp    1024
#define IDC_REQUEST_TIMESTAMP           1025
#define IDC_REPORT_SUBEQPID             1026
#define IDC_ED_OLD_PASSWORD             1027
#define IDC_REPORT_LOTID                1027
#define IDC_ED_NEW_PASSWORD             1028
#define IDC_STATIC_REPORT_LOTID         1028
#define IDC_ED_CONFIRM_PW               1029
#define IDC_REPORT_RECIPEID             1029
#define IDC_ST_OLD_PASSWORD             1030
#define IDC_STATIC_REPORT_RECIPEID      1030
#define IDC_ST_NEW_PASSWORD             1031
#define IDC_REPORT_PRODUCTID            1031
#define IDC_ST_CONFIRM_PW               1032
#define IDC_STATIC_REPORT_PRODUCTID     1032
#define IDC_REPORT_PRGVER               1033
#define IDC_STATIC_REPORT_PRGVER        1034
#define IDC_REPORT_ONLINESTATE          1035
#define IDC_STATIC_REPORT_ONLINESTATE   1036
#define IDC_REQUEST_EQUIPMENTID         1037
#define IDC_STATIC_REQUEST_EQUIPMENTID  1038
#define IDC_REQUEST_IPADDRESS           1039
#define IDC_STATIC_REQUEST_IPADDRESS    1040
#define IDC_REQUEST_USERID              1041
#define IDC_STATIC_REQUEST_USERID       1042
#define IDC_REPORT_EQUIPMENTSTATE       1043
#define IDC_STATIC_REPORT_EQUIPMENTSTATE 1044
#define IDC_REQUEST_RETURNCODE          1045
#define IDC_STATIC_REQUEST_returnCode   1046
#define IDC_REQUEST_RETURNMESSAGE       1047
#define IDC_STATIC_REQUEST_RETURNMESSAGE 1048
#define IDC_COMBO_REPORT                1049
#define IDC_BUTTON_REPORT               1050
#define IDC_BUTTON_SET_ALARMLIST        1051
#define IDC_BUTTON_SAVE_ALARMLIST       1051
#define IDC_STATIC_REPORT_SUBEQPID      1052
#define IDC_REQUEST_APPLICATIONID       1053
#define IDC_STATIC_REQUEST_USERID2      1054
#define IDC_STATIC_REQUEST_APPLICATIONID 1054
#define IDC_REPORT_LOSSSTATE            1055
#define IDC_STATIC_REPORT_LOSSSTATE     1056
#define IDC_REPORT_LOSSCOUNT            1057
#define IDC_STATIC_REPORT_LOSSCOUNT     1058
#define IDC_REQUEST_SUBEQPID            1059
#define IDC_STATIC_REQUEST_SUBEQPID     1060
#define IDC_REQUEST_EQUIPMENTSTATEDISPLAY 1061
#define IDC_STATIC_REQUEST_EQUIPMENTSTATEDISPLAY 1062
#define IDC_REQUEST_RGBDISPLAY          1063
#define IDC_STATIC_REQUEST_RGBDISPLAY   1064
#define IDC_REQUEST_LOSSWINDOW          1065
#define IDC_REQUEST_TRANSACTIONID2      1066
#define IDC_REQUEST_MESSAGENAME         1066
#define IDC_STATIC_REQUEST_MESSAGENAME  1067
#define IDC_STATIC_REQUEST_LOSSWINDOW   1068
#define IDC_REPORT_ALARMCODE            1069
#define IDC_STATIC_REPORT_ALARMCODE     1070
#define IDC_REPORT_ALARMID              1071
#define IDC_STATIC_REPORT_ALARMID       1072
#define IDC_REPORT_ALARMMESSAGE         1073
#define IDC_STATIC_REPORT_ALARMMESSAGE  1074
#define IDC_REQUEST_ALARM_LIST          1075
#define IDC_REQUEST_LIST                1075
#define IDC_REQUEST_DATETIME            1076
#define IDC_STATIC_REQUEST_DATETIME     1077
#define IDC_MFCVSLISTBOX1               1078
#define IDC_REQUEST_TERMINALMESSAGE     1078
#define IDC_STATIC_REQUEST_TERMINALMESSAGE 1079
#define IDC_REQUEST_BUZZER              1080
#define IDC_STATIC_REQUEST_BUZZER       1081
#define IDC_REQUEST_MESSAGE             1082
#define IDC_STATIC_REQUEST_MESSAGE      1083
#define IDC_REQUEST_TOWERLAMP           1084
#define IDC_STATIC_REQUEST_TOWERLAMP    1085
#define IDC_REPORT_PORTID               1086
#define IDC_STATIC_REPORT_PORTID        1087
#define IDC_REPORT_CARRIERID            1088
#define IDC_STATIC_REPORT_CARRIERID     1089
#define IDC_REPORT_CARRTYPE             1090
#define IDC_STATIC_REPORT_CARRTYPE      1091
#define IDC_REPORT_OUTCARRIERID         1092
#define IDC_STATIC_REPORT_OUTCARRIERID  1093
#define IDC_REPORT_OUTCARRTYPE          1094
#define IDC_STATIC_REPORT_OUTCARRTYPE   1095
#define IDC_REPORT_OUTCARRPORTID        1096
#define IDC_STATIC_REPORT_OUTCARRIERID2 1097
#define IDC_STATIC_REPORT_OUTCARRPORTID 1097
#define IDC_REPORT_RETRY                1098
#define IDC_STATIC_REPORT_RETRY         1099
#define IDC_REPORT_LIST                 1100
#define IDC_REPLY_LIST                  1101
#define IDC_STATIC_REPLY                1102
#define IDD_DLG_ERR                     1103
#define IDC_COMBO_REPLY                 1103
#define IDC_REPLY_TRANSACTIONID         1104
#define IDD_DLG_POPUP                   1105
#define IDC_STATIC_REPORT_transactionId2 1105
#define IDC_STATIC_REPORT_TimeStamp2    1106
#define IDC_REPLY_TIMESTAMP             1107
#define IDC_REPLY_EQUIPMENTID           1108
#define IDC_STATIC_REPLY_EQUIPMENTID    1109
#define IDC_REPLY_IPADDRESS             1110
#define IDC_STATIC_REPLY_IPADDRESS      1111
#define IDC_STATIC_REQUEST_BODY2        1112
#define IDC_REPLY_APPLICATIONID         1113
#define IDC_STATIC_REPLY_APPLICATIONID  1114
#define IDC_STATIC_REPLY_RETURN         1115
#define IDC_REPLY_RETURNCODE            1116
#define IDC_STATIC_REPLY_returnCode     1117
#define IDC_REPLY_RETURNMESSAGE         1118
#define IDC_STATIC_REPLY_RETURNMESSAGE  1119
#define IDC_BUTTON_DATACLEAR            1120
#define IDC_REPLY_USERID                1121
#define IDC_STATIC_REPLY_USERID         1122
#define IDC_REPLY_SUBEQPID              1123
#define IDC_STATIC_REPLY_SUBEQPID       1124
#define IDC_REPLY_EQUIPMENTSTATEDISPLAY 1125
#define IDC_STATIC_REPLY_EQUIPMENTSTATEDISPLAY 1126
#define IDC_REPLY_RGBDISPLAY            1127
#define IDC_STATIC_REPLY_RGBDISPLAY     1128
#define IDC_REPLY_LOSSWINDOW            1129
#define IDC_STATIC_REQUEST_LOSSWINDOW2  1130
#define IDC_REPLY_DATETIME              1131
#define IDC_STATIC_REPLY_DATETIME       1132
#define IDC_REPLY_TERMINALMESSAGE       1133
#define IDC_STATIC_REQUEST_TERMINALMESSAGE2 1134
#define IDC_REPLY_MESSAGE               1135
#define IDC_STATIC_REply_MESSAGE        1136
#define IDC_REPLY_BUZZER                1137
#define IDC_STATIC_REPLY_BUZZER         1138
#define IDC_REPLY_TOWERLAMP             1139
#define IDC_STATIC_REPLY_TOWERLAMP      1140
#define IDC_BUTTON_SAVE_UNITID_READ     1141
#define IDC_FILEDATA_LIST               1142
#define IDC_REPORT_EQPTYPECODE          1143
#define IDC_STATIC_REPORT_EQPTYPECODE   1144
#define IDC_REPORT_STEPID               1145
#define IDC_STATIC_REPORT_STEPID        1146
#define IDC_REPORT_SWVERSION            1147
#define IDC_STATIC_REPORT_SWVERSION     1148
#define IDC_MESSAGE_STATIC_TITLE        1149
#define IDC_REPORT_SWHASHCODE           1149
#define IDC_MESSAGE_STATIC_SUBTITLE     1150
#define IDC_STATIC_REPORT_SWHASHCODE    1150
#define IDC_REPORT_SWMODULETYPE         1151
#define IDC_STATIC_REPORT_SWMODULETYPE  1152
#define IDC_MESSAGE_STATIC_LINE         1153
#define IDC_REPORT_CONSUMLIST           1153
#define IDC_STATIC_REPORT_CONSUMLIST    1154
#define IDC_REPORT_LIST2                1155
#define IDC_REQUEST_EQPTYPECODE         1156
#define IDC_STATIC_REQUEST_EQPTYPECODE  1157
#define IDC_REQUEST_LOTID               1158
#define IDC_STATIC_REQUEST_LOTID        1159
#define IDC_BUTTON_REPLY_UNITID_LIST    1160
#define IDC_REPLY_LIST2                 1161
#define IDC_REQUEST_PRODUCTID           1162
#define IDC_STATIC_REQUEST_PRODUCTID    1163
#define IDC_REQUEST_PORTID              1164
#define IDC_STATIC_REQUEST_PORTID       1165
#define IDC_REQUEST_STEPID              1166
#define IDC_STATIC_REQUEST_STEPID       1167
#define IDC_BUTTON3                     1168
#define IDC_BUTTON_REPORT_DATACLEAR     1168
#define IDC_BUTTON_REQUEST_DATACLEAR    1169
#define IDC_BUTTON_REPLY_DATACLEAR      1170
#define IDC_REPLY_LOTID                 1171
#define IDC_STATIC_REPLY_LOTID          1172
#define IDC_LIST_ID_CONFIG              1172
#define IDC_COMBO1                      1173
#define IDC_REQUEST_CONSUMLIST          1184
#define IDC_STATIC_REQUEST_CONSUMLIST   1185
#define IDC_REPLY_CONSUMLIST            1186
#define IDC_STATIC_REPLY_CONSUMLIST     1187
#define IDC_REPLY_PORTID                1188
#define IDC_STATIC_REPLY_PORTID         1189
#define IDC_REPLY_PRODUCTID             1190
#define IDC_STATIC_REPLY_PORTID2        1191
#define IDC_STATIC_REPLY_PRODUCTID      1191
#define ID_TABVIEW_1                    3001
#define ID_TABVIEW_2                    3002
#define ID_TABVIEW_3                    3003
#define ID_TABVIEW_4                    3004
#define ID_TABVIEW_5                    3005
#define ID_TABVIEW_6                    3006
#define ID_TABVIEW_7                    3007
#define ID_TABVIEW_8                    3008
#define ID_TABVIEW_9                    3009
#define IDD_DIALOG_MESSAGE              30014
#define IDD_DLG_MODIFY_NGCODE           30015
#define IDD_DLG_MODIFY_SV1              30016
#define IDD_DLG_MODIFY_AL               30016
#define ID_Menu                         40001
#define ID_40002                        40002
#define ID_40003                        40003
#define ID_40004                        40004
#define ID_CAPTION_DELETE               40005
#define ID_CAPTION_SHOW                 40006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         40007
#define _APS_NEXT_CONTROL_VALUE         1175
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
